### ISSUE TITLE
Konsekvent API för user.

### ISSUE THREAD

**Issue by MathiasKindberg** [CommuteCompanion/etsn05-project#158]
APIn för user är inte konsekvent vilket gör den extremt klumpig att använda. putUser och postUser funktionerna vill ha credentials objekt medan getUser och getUsers returnerar user objekt vilket är ett underobjekt till credentials.

Det gör att det en så enkel funktion som denna inte fungerar eftersom user objektet inte stämmer överrens och jag inte kan få tag på den resterande datan för att fylla i de "tomma" fälten i credentialsobjektet.... (Vilket även det hade varit en riktigt riktigt ful lösning.)

```
giveWarning: function(user) {
            user.warning = user.warning + 1;
            window.base.rest.putUser(user.userId, user);
        }
```

**Comment by antondelorme** [comment]
`putUser` är menad, som namnet antyder, att sätta in en (ny) användare. Put-(a)-User in database. Den används också av user-profile då man kanske vill uppdatera lösenord, man behöver alltså Credentials (samma sak när det gäller registrering såklart). 
Det du vill göra `giveWarning(userId)` borde anropa en annan funktion i rest; t.ex. `giveUserWarning(int userId)` (den funktionen finns inte, man får skriva den, men det blir långt mycket enklare än att ändra putUser)
