### ISSUE TITLE
Editing a drive seems to either delete it or corrupt its data

### ISSUE THREAD

**Issue by antondelorme** [CommuteCompanion/etsn05-project#244]
Create a drive -> go to "My commutes" -> click Edit -> change something and click "Edit Drive".

The drive no longer shows in the list of "My commutes" and Find-tab shows:

 "Something went wrong, error message: Cannot read property 'firstName' of undefined."

**Comment by arpi09** [comment]
Seems like the drive is stil in the database

**Comment by jost95** [comment]
@antondelorme @arpi09 driver sätts till false för första användaren i databasen, därav FE fel
