### ISSUE TITLE
Add accept button

### ISSUE THREAD

**Issue by jacobagardh** [CommuteCompanion/etsn05-project#322]
When a passenger request to join a drive the driver should be able to accept/decline the passenger.

Could not find an accept button. This should be added.

**Comment by arpi09** [comment]
Buttons now exist, but the process doesnt work correctly

**Comment by arpi09** [comment]
Behöver jobbas på i BE @jacobagardh @McPoppe

**Comment by arpi09** [comment]
Fixat nu, låg på FE
