### ISSUE TITLE
Add XSS filter as a backend provider in Jersey

### ISSUE THREAD

**Issue by jost95** [CommuteCompanion/etsn05-project#79]
Something in the lines of https://dzone.com/articles/stronger-anti-cross-site

**Comment by antondelorme** [comment]
Don't make this a priority. We have far more important things to implement than this.

Consider that it might be quick to implement, but it also needs to be actively tested as it is a security feature. We do not have the manpower or time atm to do in-depth js-injection attacks. 

SRS does not specify that we need protection against these types of attacks. Nor do I think our customer will care.

**Comment by jost95** [comment]
Out of scope
